donations/urls.py
from django.urls import path

from . import views

app_name = "donations"
urlpatterns = [
    # path("", views.index, name="index"),
    path("view/", views.index, name="index"),
    path("donate/", views.donate, name="donate"),
    # path("kotk_form/<str:first_name>/<str:last_name>/<str:amount>/", views.kotk_form, name="kotk_form"),
    path("getCurrentTotal/", views.get_current_total_async, name="get_current_total_async"),
]

donationtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("donations/", include("donations.urls", namespace="donations")),
    path("running/", include("running.urls", namespace="running")),
    path("admin/", admin.site.urls),
]

running/urls.py
from django.urls import path

from . import views

app_name = "running"
urlpatterns = [
    path("", views.index, name="index"),
    path("addLapAsync/", views.add_lap_async, name="add_lap_async"),
]

donations/models.py
from django.db import models

class Donation(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    amount = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

running/models.py
from django.db import models
from django.utils import timezone

class Team(models.Model):
    name = models.CharField(max_length=255, default="Anoteam")
    origin = models.CharField(max_length=255, default="Weerde")

class Participant(models.Model):
    name = models.CharField(max_length=255, default="Anoniem")
    number = models.CharField(max_length=3, default="")
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    strava_user_id = models.CharField(max_length=255, null=True, blank=True, default="")

class Lap(models.Model):
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)

donations/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.urls import reverse
from django.db.models import Sum
from .models import Donation

def index(request):
    total_amount = Donation.objects.all().aggregate(Sum("amount")).get("amount__sum", 10)
    context = {
        "total_amount": total_amount
    }
    return render(request, "donations/index.html", context)

def donate(request):

    # The first section for POST processes input if there was any, adding the donation. After that we render the form in all cases.

    if request.method == "POST":
        try:
            amount = request.POST.get("amount", 50)
            first_name = request.POST.get("firstName", None)
            last_name = request.POST.get("lastName", None)
            donation = Donation(first_name=first_name, last_name=last_name, amount=amount)
            donation.save()
            messages.success(request, "Vervolledig het officiële KotK giftenformulier om de gift af te werken!")
            context = {
                "first_name": first_name,
                "last_name": last_name,
                "amount": amount
            }
            return render(request, "donations/kotk_form.html", context=context)
        except Exception as e:
            messages.error(request, "Er was een probleem met de ingegeven gift.")
            print(e)
            return render(request, "donations/donate.html")

    else:
        return render(request, "donations/donate.html")
    

def get_current_total_async(request):

    try:
        total_amount = Donation.objects.all().aggregate(Sum("amount")).get("amount__sum", 0)
        response = {
            "total_amount": total_amount
        }
        return JsonResponse(response)
    except Exception as e:
        print(e)

running/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import Participant, Team, Lap

import json

# Create your views here.

def index(request):
    teams = Team.objects.all().order_by("id")
    participants = Participant.objects.all().order_by("number")
    context = {}
    context["teams"] = []
    for team in teams:
        team_participants = []
        for team_participant in [p for p in participants if p.team == team]:
            team_participant_laps = Lap.objects.filter(participant=team_participant).count()
            team_participants.append({
                "name": team_participant.name,
                "number": team_participant.number,
                "participant": team_participant,
                "laps": team_participant_laps
            })
        context["teams"].append({
            "name": team.name,
            "team": team,
            "participants": team_participants,
            "total_laps": sum([p["laps"] for p in team_participants])
        })

    return render(request, "running/index.html", context)

def add_lap_async(request):

    try:
        request_json = json.loads(request.body)
        participant_id = request_json["participantId"]
        new_lap = Lap.objects.create(participant_id=participant_id)
        participant_total_laps = Lap.objects.filter(participant_id=participant_id).count()
        
        response = {
            "new_lap_timestamp": new_lap.timestamp,
            "participant_total_laps": participant_total_laps
        }
        return JsonResponse(response)
    
    except Exception as e:
        print(e)

donationtracker/templates/donations/donate.html
{% extends "layouts/base_kotk.html" %}
{% load static %}
{% block content %}

    <div id="header" class="header w-100 text-center m-0 pb-2">
        <p class="m-0">Weit steunt Kom Op Tegen Kanker</p>
    </div>

    <div class="form-float-container w-100">

        <form class="w-100" action="{% url 'donations:donate' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                <div class="row w-100">

                <div id="amount-preview-area" class="form-float-child-h">
                    <p class="kilo-text">&euro; <span id="amount-preview">100</span></p>
                </div>
                
                <div id="input-knob" class="form-float-child-q">
                    <label for="amount" class="mt-2">Bedrag</label>
                    <!-- <input type="text" name="amount" id="amount" class="form-control input-lg" placeholder="50"> -->
                    <input-knob value="50" scale="50" min="5" max="500" name="amount-knob" id="amount-knob">
                        <div class="mark">▲</div>
                    </input-knob>
                    <input type="hidden" id="amount" name="amount" value="50">
                </div>

                </div>

                <div class="row w-100">

                    <div id="input-details" class="row w-100 ml-3">
                        <div class="col-5">
                            <label for="firstName" class="mt-3">Voornaam</label>
                            <input type="text" name="firstName" id="firstName" class="form-control input-lg" placeholder="Jeanke">
                        </div>
                        <div class="col-5">
                            <label for="lastName" class="mt-3">Naam</label>
                            <input type="text" name="lastName" id="lastName" class="form-control input-lg" placeholder="Van Omdenhoek">
                        </div>
                        <div class="col-2">
                            <input type="submit" value="Gift maken" class="btn btn-warning mt-5 w-100">
                        </div>
                    </div>

                </div>
        </form>

    </div>

    <script src="{% static '/js/donations.js' %}"></script>

{% endblock content %} 

donationtracker/templates/donations/index.html
{% extends "layouts/base_kotk.html" %}
{% load static %}
{% block content %}

    <!-- Listing available audio/media here so we benefit from static, then using these vars in JS later. -->
    <script>
        const audioSamples = [
            "{% static '/media/fanfare.wav' %}",
            "{% static '/media/cheer1.wav' %}",
            "{% static '/media/cheer2.wav' %}",
            "{% static '/media/charge.wav' %}",
            "{% static '/media/airhorn.mp3' %}"
        ];
    </script>

    <div class="container-fluid p-0">
        <div class="row w-100 p-0 m-0">
            <div class="col-12 w-100 p-0 m-0">
                <div id="header" class="header w-100 text-center m-0 pb-2">
                    <p class="m-0">Weit steunt Kom Op Tegen Kanker</p>
                </div>
                <div id="giften" class="w-100 text-center">

                    {% if total_amount %}
                    <p class="mt-4 micro-text">Totaal giften tot nu toe:</p>
                    <h1 class="mt-4 mega-text animate__animated animate__tada" id="total-donations-full">&euro; <span id="total-donations">{{ total_amount }}</span></h1>
                    {% else %}
                    <h2>Geen</h2>
                    {% endif %}

                    <audio id="audio" preload="auto" loop="False" src="{% static '/media/fanfare.wav' %}"></audio>

                </div>
            </div>
        </div>
    </div>

    <script src="{% static '/js/donations.js' %}"></script>

{% endblock content %} 

donationtracker/templates/donations/kotk_form.html
{% extends "layouts/base_kotk.html" %}
{% load static %}
{% block content %}

    <!-- "Inline" variables we can use in donations.js -->
    <script>
        let firstName = "{{ first_name }}";
        let lastName = "{{ last_name }}";
        let amount = "{{ amount }}";
    </script>

    <!-- Scripts used for x-frame-bypass (https://github.com/niutech/x-frame-bypass) -->
    <script src="https://unpkg.com/@ungap/custom-elements-builtin"></script>
    <script type="module" src="{% static '/plugins/x-frame-bypass/js/x-frame-bypass.js' %}"></script>

    <div id="header" class="header w-100 text-center m-0 pb-2">
        <p class="m-0">Weit steunt Kom Op Tegen Kanker</p>
    </div>

    
    <!-- Back button -->
    <div id="backButton" onclick="history.back()">
        <p style="margin-top: -12px;">&lsaquo;</p>
    </div>

    <style>
        #backButton {
            position: absolute;
            top: 5px;
            right: 5px;
            width: 50px;
            height: 50px;
            border-radius: 50%;
            background: #666666;
            color: #ddaf2d;
            font-size: 36pt;
            text-align: center;
            cursor: pointer;
        }
    </style>


    <div class="form-float-container">

    <iframe id="kotkForm" is="x-frame-bypass" src="https://www.komoptegenkanker.be/de-100km-run/doe-een-gift?team_id=340141860"></iframe>
    <!-- https://www.komoptegenkanker.be/de-100km-run/doe-een-gift?team_id=340141860 -->

    </div>

    <script src="{% static '/js/donations.js' %}"></script>

{% endblock content %} 

donationtracker/templates/layouts/base_kotk.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        Weit steunt Kom Op Tegen Kanker
    </title>

    <meta charset="utf-8">

    {% block stylesheets %}
        <!-- <link rel="stylesheet" href="{% static '/fonts/fontawesome/css/fontawesome-all.min.css' %}"> -->
        <link rel="stylesheet" href="{% static '/plugins/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static '/plugins/animate/css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock stylesheets %}

    {% block fonts %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Signika+Negative:wght@500&display=swap" rel="stylesheet">
    {% endblock fonts %}

</head>
<body>

    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <p class="message {% if message.tags %} {{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </div>
    {% endif %}
    
    {% block content %}{% endblock content %}
    
    {% block javascripts %}
        <script src="{% static '/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static '/plugins/jquery/js/jquery.min.js' %}"></script>
        <script src="https://unpkg.com/input-knob"></script>
    {% endblock javascripts %}

</body>
</html>

donationtracker/templates/running/index.html
{% extends "layouts/base_kotk.html" %}
{% load static %}
{% block content %}

    <script>
        let csrf_token = "{{ csrf_token }}";
    </script>

    <div class="container-fluid p-0">
        <div class="row w-100 p-0 m-0">
            <div class="col-12 w-100 p-0 m-0">
                <div id="header" class="header w-100 text-center m-0 pb-2">
                    <p class="m-0">Weit steunt Kom Op Tegen Kanker</p>
                </div>
                <div id="running-tracker" class="w-100">

                    <div class="">
                        {% if teams %}
                            {% for team in teams %}
                                <div class="card float-left" style="width: 18rem;">
                                    <div class="card-header">
                                        <span class="team-name">{{ team.team.id }} | {{ team.name }}</span>
                                        <span class="team-laps">{{ team.total_laps }}</span>
                                    </div>
                                    {% if team.participants %}
                                    <ul class="list-group list-group-flush">
                                        {% for participant in team.participants %}
                                        <li class="list-group-item">
                                            <div class="participant" id="participant-id-{{participant.participant.id}}">
                                                <span class="participant-name">{{ participant.participant.number }} | {{ participant.name }}</span>
                                                <span class="participant-laps">{{ participant.laps }}</span>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script src="{% static '/js/running.js' %}"></script>

{% endblock content %} 